### ISSUE TITLE
Checkbox is on incorrect side of AWS icon

### ISSUE THREAD

**Issue by mwalker5000** [rht-labs/infographic#25]
Looks like the checkbox for AWS (in hosting infrastructure) should be on the left, but is actually on the right side.

![screenshot 2018-01-26 14 13 55](https://user-images.githubusercontent.com/1175183/35462954-2edf3b22-02a3-11e8-975a-a3c8b653e7f7.png)

@rdebeasi can you please have a look?

**Comment by rdebeasi** [comment]
Addressed by #27
