### ISSUE TITLE
Add Red Hat Application Migration Toolkit to infographic

### ISSUE THREAD

**Issue by mwalker5000** [rht-labs/infographic#28]
Let's add RHAMT to infographic. Let's put it under Application Development / Red Hat Enterprise Open Source.

There is no icon to my knowledge (though it may be worth checking with the team to be sure they don't have something in the works that might be available). 

We could use pure text, like the other Red Hat logos, or could perhaps incorporate the Red Hat Developers icon, plus AMT text --
 your choice if no logo is available.

Website is here:
https://developers.redhat.com/products/rhamt/overview/

This toolkit plugs into Eclipse and has been used at Labs so let's start advertising it!

**Comment by rdebeasi** [comment]
Cool, will do! I was able to track down [this logo](https://pnt.redhat.com/pnt/p-5294183/Logotype_RH_AMT_RGB_Black.png) (requires VPN), so I think I have everything I need to add this icon.
