### ISSUE TITLE
Is it possible to automate creation of web hooks? 

### ISSUE THREAD

**Issue by InfoSec812** [rht-labs/infographic#38]

**Comment by oybed** [comment]
@InfoSec812 Creating Web Hooks can be automated within the template deployed. However, the challenge is that it requires additional "manual setup" in the target repo - e.g.: in github. Hence, it tends to be "beyond the scope" of a demo as it will require additional insight knowledge + require setup time that is confusing during a demo run.

**Comment by oybed** [comment]
Closing for now - we can discuss it again later on if needed.
