### ISSUE TITLE
Add standard Red Hat footer to infographic

### ISSUE THREAD

**Issue by rdebeasi** [rht-labs/infographic#42]
Add footer for consistency with other Red Hat properties. From the corporate style guide, via Jennifer Calogero:

>Please familiarize yourself with the corporate style guide for web properties:
>
>[Official Red Hat Unified Web Style Guide](https://mojo.redhat.com/external-link.jspa?url=https%3A%2F%2Fdocs.google.com%2Fa%2Fredhat.com%2Fdocument%2Fd%2F1bAb9MkrLW34wtk4RtrYvqLylXnvWhS81aDHAjhSzxMQ%2Fedit%3Fusp%3Dsharing)
>
>Red Has requires most web properties include [header](https://mojo.redhat.com/external-link.jspa?url=https%3A%2F%2Fredhat.invisionapp.com%2Fboards%2F892NGCHYQWVEH%2F) and footer elements to maintain brand continuity. The main thing that applies to campaigns from this guide are the header and footer styles ([1](https://mojo.redhat.com/external-link.jspa?url=https%3A%2F%2Fdrive.google.com%2Fa%2Fredhat.com%2Ffile%2Fd%2F0Bx_YRjuf-_yQbnBFcjBpa2QxeWc%2Fview%3Fusp%3Dsharing) | [2](https://mojo.redhat.com/external-link.jspa?url=https%3A%2F%2Fdrive.google.com%2Fa%2Fredhat.com%2Ffile%2Fd%2F0Bx_YRjuf-_yQbzdzWjdmTGFuX0E%2Fview%3Fusp%3Dsharing)).Footer style 1 shown here, if used, should be populated with only links relevant to your microsite. In most cases, footer style 2 will be used. Please integrate these elements into your design for brand continuity.

**Comment by oybed** [comment]
Resolve with #43
