### ISSUE TITLE
Add Dynatrace to the Infographic content

### ISSUE THREAD

**Issue by oybed** [rht-labs/infographic#49]
A new logo for Dynatrace should be added to the Infographic, in the `MONITORING AND LOGGING` section.

Description: 
> Dynatrace - Performance management software for programs running on-premises and in the cloud

Logo:
https://assets.dynatrace.com/content/dam/dynatrace/misc/dynatrace_web.png

**Comment by peterhack** [comment]
Description:

Dynatrace - Full-stack monitoring for applications in the enterprise cloud

**Comment by peterhack** [comment]
Logo: 
![dynatrace_logo_rgb-html_horizontal_gray](https://user-images.githubusercontent.com/6146091/42183328-608c0de8-7e0f-11e8-91e4-81a4e0129ae1.png)

**Comment by oybed** [comment]
@peterhack thanks for providing the the info/updated description so quickly  - appreciate it.

@rdebeasi can you please update the PR with the above info?

**Comment by rdebeasi** [comment]
Sure - updated!
